-- Standardize S0SADC to the shared Smartis schema (matches e-Invoice).
-- Non-destructive: never drops the table, columns, or rows.
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'S0SADC')
BEGIN
    CREATE TABLE [S0SADC] (
        [ID] INT IDENTITY(1,1) PRIMARY KEY,
        [NAME] NVARCHAR(20) NOT NULL,
        [VERSION] NVARCHAR(10) NOT NULL,
        [PROVIDER] NVARCHAR(10) NOT NULL DEFAULT 'SMARTIS',
        [TYPE] NVARCHAR(10) NOT NULL DEFAULT 'LightAddon',
        [INSTCOMPNY] NVARCHAR(50) NULL,
        [INSTALLDATE] DATE NOT NULL,
        [INSTALLUSER] NVARCHAR(50) NOT NULL,
        [INSTALLKEY] NVARCHAR(MAX) NULL,
        [SHKEY] NVARCHAR(50) NULL,
        [STARTDATE] DATE NULL,
        [ENDDATE] DATE NULL,
        [CUSTOMERNAME] NVARCHAR(100)
    );
END;

-- Rename legacy typo column INSTALLGUSER -> INSTALLUSER (keeps data)
IF COL_LENGTH('dbo.S0SADC', 'INSTALLUSER') IS NULL AND COL_LENGTH('dbo.S0SADC', 'INSTALLGUSER') IS NOT NULL
    EXEC sp_rename 'dbo.S0SADC.INSTALLGUSER', 'INSTALLUSER', 'COLUMN';

-- Add columns missing on older installs (keeps data)
IF COL_LENGTH('dbo.S0SADC', 'SHKEY') IS NULL
    ALTER TABLE [S0SADC] ADD [SHKEY] NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.S0SADC', 'STARTDATE') IS NULL
    ALTER TABLE [S0SADC] ADD [STARTDATE] DATE NULL;

IF COL_LENGTH('dbo.S0SADC', 'ENDDATE') IS NULL
    ALTER TABLE [S0SADC] ADD [ENDDATE] DATE NULL;

IF COL_LENGTH('dbo.S0SADC', 'CUSTOMERNAME') IS NULL
    ALTER TABLE [S0SADC] ADD [CUSTOMERNAME] NVARCHAR(100) NULL;

-- Widen legacy INSTALLKEY (ntext / bounded nvarchar) to NVARCHAR(MAX) (keeps data)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'S0SADC' AND COLUMN_NAME = 'INSTALLKEY'
             AND (DATA_TYPE = 'ntext' OR (DATA_TYPE = 'nvarchar' AND CHARACTER_MAXIMUM_LENGTH <> -1)))
    ALTER TABLE [S0SADC] ALTER COLUMN [INSTALLKEY] NVARCHAR(MAX) NULL;
