CREATE OR REPLACE PROCEDURE "VASGetAddonInfo"
    (
        IN ExtName NVARCHAR(100),
        IN ExtVersion NVARCHAR(100),
        IN Partner NVARCHAR(100)
    )
		LANGUAGE SQLSCRIPT
		SQL SECURITY INVOKER
		AS
BEGIN
	SELECT TOP 1
	    A.NAME,
	    A.VERSION,
	    A.PROVIDER,
	    '' AS EIPROVIDER,
	    A.CUSTOMERNAME,
	    A.ENDDATE,
		CAST(A.INSTALLKEY AS NVARCHAR(4000)) AS "INSTALLKEY"
	FROM S0SADC A
	WHERE
	    A.NAME = :ExtName
	    AND A.VERSION = :ExtVersion
	    AND A.PROVIDER = :Partner
	ORDER BY A.ID DESC;
END;
