-- Standardize S0SADC to the shared Smartis schema (matches e-Invoice).
-- Non-destructive: never drops the table, columns, or rows.
DO
BEGIN
    If not exists (
        Select top 1 table_name from sys.tables
        where schema_name = CURRENT_SCHEMA and lower(table_name) = lower('S0SADC')
    ) then
        EXEC 'CREATE COLUMN TABLE "S0SADC"
            ("ID" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
             "NAME" NVARCHAR(20) NOT NULL ,
             "VERSION" NVARCHAR(10) NOT NULL ,
             "PROVIDER" NVARCHAR(10) NOT NULL DEFAULT ''SMARTIS'',
             "TYPE" NVARCHAR(10) NOT NULL DEFAULT ''LightAddon'',
             "INSTCOMPNY" NVARCHAR(50) NULL,
             "INSTALLDATE" DATE CS_DAYDATE NOT NULL ,
             "INSTALLUSER" NVARCHAR(50) NOT NULL ,
             "INSTALLKEY" NCLOB,
             "SHKEY" NVARCHAR(50),
             "STARTDATE" DATE CS_DAYDATE,
             "ENDDATE" DATE CS_DAYDATE,
             "CUSTOMERNAME" NVARCHAR(100),
             PRIMARY KEY ("ID"))';
    End if;

    -- Rename legacy typo column INSTALLGUSER -> INSTALLUSER (keeps data)
    If exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'INSTALLGUSER')
       and not exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'INSTALLUSER') then
        EXEC 'RENAME COLUMN "S0SADC"."INSTALLGUSER" TO "INSTALLUSER"';
    End if;

    -- Add columns missing on older installs (keeps data)
    If not exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'SHKEY') then
        EXEC 'ALTER TABLE "S0SADC" ADD ("SHKEY" NVARCHAR(50))';
    End if;

    If not exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'STARTDATE') then
        EXEC 'ALTER TABLE "S0SADC" ADD ("STARTDATE" DATE)';
    End if;

    If not exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'ENDDATE') then
        EXEC 'ALTER TABLE "S0SADC" ADD ("ENDDATE" DATE)';
    End if;

    If not exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'CUSTOMERNAME') then
        EXEC 'ALTER TABLE "S0SADC" ADD ("CUSTOMERNAME" NVARCHAR(100))';
    End if;

    -- Widen legacy INSTALLKEY to NCLOB (keeps data)
    If exists (Select top 1 column_name from table_columns where schema_name = CURRENT_SCHEMA and table_name = 'S0SADC' and column_name = 'INSTALLKEY' and data_type_name <> 'NCLOB') then
        EXEC 'ALTER TABLE "S0SADC" ALTER ("INSTALLKEY" NCLOB)';
    End if;
END;
