CREATE OR ALTER PROCEDURE VASGetAddonInfo
    @ExtName NVARCHAR(100),
    @ExtVersion NVARCHAR(100),
    @Partner NVARCHAR(100)
AS
BEGIN
    SELECT TOP 1
	    A.NAME,
	    A.VERSION,
	    A.PROVIDER,
	    '' AS EIPROVIDER,
	    A.CUSTOMERNAME,
	    A.ENDDATE,
		CAST(A.INSTALLKEY AS NVARCHAR(4000)) AS INSTALLKEY
	FROM S0SADC A
	WHERE
	    A.NAME = @ExtName
	    AND A.VERSION = @ExtVersion
	    AND A.PROVIDER = @Partner
	ORDER BY A.ID DESC
END
